name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo test

  deploy:
    name: DEPLOY
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo deploy